generation-properties:
  target-root-path: "C:\\Users\\lantum\\wasm-mockgen\\platform\\out"
  frontend-properties:
    project-type: module
    test-framework: mocha
  configs:
    my-store-service:
      adapter: go
      mappings-root: /my-store/
      backend-source-path: "C:\\Users\\lantum\\backend-my-store"